version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: myuser@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:

